estaciones = {1: "P. Recoletos",
              2: "Glta. de Carlos V", 
              35: "Plaza del Carmen", 
              4: "Pza. de España", 
              39: "Barrio del pilar",
              6: "Pza. Dr. Marañon", 
              7: "Pza. M. de Salamanca", 
              8: "Escuelas aguirre", 
              9: "Pza. Luca de Tena", 
              38: "Cuatro caminos",
              11: "Av. Ramon y Cajal", 
              12: "Pza. Manuel Becerra", 
              40: "Vallecas", 
              14: "Pza. Fdez. Ladreda", 
              15: "Pza. Castilla", 
              16: "Arturo Soria",
              17: "Villaverde Alto", 
              18: "Calle Farolito",
              19: "Huerta Castañeda",
              36: "Morataz",
              21: "Pza. Cristo Rey",
              22: "P°. Fontones",
              23: "Final C/ Alcala",
              24: "Casa de campo",
              25: "Santa Eugenia",
              26: "Urb. Embajada (Barajas)",
              27: "Barajas",
              47: "Mendez Alvaro",
              48: "P°. Castellana",
              49: "Retiro",
              50: "Pza. Castilla",
              54: "Ensanche Vallecas",
              55: "Urb. Embajada (Barajas)",
              56: "Plaza Eliptica", 
              57: "Sanchincharro", 
              58: "El Pardo", 
              59: "Parque Juan Carlos 1°",
              60: "Tres Olivos"}

contaminantes = {1: "Dioxido de Azufre",
                 6: "Monoxido de Carbono", 
                 7: "Monoxido de Nitrogeno", 
                 8: "Dioxido de Nitrogeno", 
                 9: "Particulas < 2.5 um",
                 10: "Particulas < 10 um", 
                 12: "Oxidos de Nitrogeno", 
                 14: "Ozono", 
                 20: "Tolueno", 
                 30: "Benceno", 
                 35: "Etilbenceno", 
                 37: "Metaxileno", 
                 38: "Paraxileno",
                 39: "Ortoxileno", 
                 42: "Hidrocarburos totales(hexano)", 
                 43: "Metano", 44: "Hidrocarburos no metánicos (hexano)"}

dias = ["D01", "D02", "D03", "D04", "D05", "D06",
        "D07", "D08", "D09", "D10", "D11", "D12",
        "D13", "D14", "D15", "D16", "D17", "D18",
        "D19", "D20", "D21", "D22", "D23", "D24",
        "D25", "D26", "D27", "D28", "D29", "D30",
        "D31"]

conversionDic = {'D01':  1, "D02":  2, "D03":  3, "D04":  4, "D05":  5, "D06":  6, "D07":  7, "D08":  8,
                 "D09":  9, "D10": 10, "D11": 11, "D12": 12, "D13": 13, "D14": 14, "D15": 15, "D16": 16,
                 "D17": 17, "D18": 18, "D19": 19, "D20": 20, "D21": 21, "D22": 22, "D23": 23, "D24": 24,
                 "D25": 25, "D26": 26, "D27": 27, "D28": 28, "D29": 29, "D30": 30, "D31": 31}


columnasFiltradas = ["ESTACION",
                     "MAGNITUD",
                     "ANO",
                     "MES"]

